services:
    product_factory:
        class: Bamiz\ScreamingWebshop\Infrastructure\DumbProductFactory

    create_product_use_case:
        class: Bamiz\ScreamingWebshop\CreateProduct
        arguments: ['@product_factory']
